<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>COMMIT_EDITMSG</string>
	</array>
	<key>name</key>
	<string>COMMIT_EDITMSG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>comment.commit</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.*</string>
			<key>name</key>
			<string>string.commit.text</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>git.commit.editmsg</string>
	<key>uuid</key>
	<string>4cf9b540-3e3c-11e3-aa6e-0800200c9a66</string>
</dict>
</plist>
