<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>git-rebase-todo</string>
	</array>
	<key>name</key>
	<string>git-rebase-todo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>comment.rebase-todo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\W*(pick|reword|edit|squash|fixup|exec|p|r|e|s|f|x)\s([\da-zA-Z]{4,})\s(.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.action.rebase</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.commit.hash</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.commit.text</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.rebase.todo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.*</string>
			<key>name</key>
			<string>invalid.illegal.malformed-rebase-commit</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>git.rebase.todo</string>
	<key>uuid</key>
	<string>dbc864b0-3e3c-11e3-aa6e-0800200c9a66</string>
</dict>
</plist>
